remote_theme: pmarsceill/just-the-docs

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/"
]

collections:
  posts:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    posts:

title: Kaiqianglee's algorithm
footer_content: "Copyright &copy; 2022 by Kaiqianglee"

